# Quick editing rc.conf
map X chain shell nvim -p ~/.config/ranger/rc.conf %rangerdir/config/rc.conf; source ~/.config/ranger/rc.conf
# Smart "cw"
map cw eval fm.execute_console("bulkrename") if fm.thisdir.marked_items else fm.open_console("rename ")
# Set image preview and method
set preview_images true
# set preview_images_method ueberzug
set preview_images_method kitty

# set git integration
set vcs_aware true
# devicons
default_linemode devicons2
# Send selected file(s) to trash
map DD shell mv -i %s ~/.local/share/Trash/files/ && echo "trashed %s        from_dir $(pwd)" >> ~/.config/ranger/trash_history 
map uD shell fileToRestore=$(cat ~/.config/ranger/trash_history | grep "^trashed" | tail -n 1 | cut -c10- | awk -F"from_dir " '{print $1}' | rev | cut -c10- | rev) && mv -i ~/.local/share/Trash/files/"$fileToRestore" "$fileToRestore" && echo "         untrashed $(pwd)/"$fileToRestore"" >> ~/.config/ranger/trash_history && unset fileToRestore
map Dh shell less ~/.config/ranger/trash_history
# filter as you type
map f console scout -ftsea%space
# fzf filter
map gz console fzf_filter%space
# recursive search
map F  chain flat 5 ; console scout -ftsea%space
# fzf
map <A-f> fzf_select
# fd
map <alt>/ console fd_search -d5%space 
map <alt>n fd_next
map <alt>p fd_prev
# fzf in home dir
map <alt>h fzf_content_open 
