require("helpers.monitor_setup")
require("helpers.startup_procs")
require("helpers.envs")
require("helpers.general_conf")
require("helpers.animations")
require("helpers.gestures")
require("helpers.devices")
require("helpers.window_rules")
require("helpers.keymaps")
require("helpers.utils.zoom")

