preload = /home/mkc/Pictures/wallpapers/80s-Neon-City-Wallpapers-Top-Free-80s-Neon-City-.png
wallpaper = ,/home/mkc/Pictures/wallpapers/80s-Neon-City-Wallpapers-Top-Free-80s-Neon-City-.png
splash = true
