windowrule = float, ^(thunar)$
windowrule = size 1000 600, ^(thunar)$
windowrule = center, ^(thunar)$

windowrule = float, title:(Thunar)
windowrule = size 1000 600, title:(Thunar)
windowrule = center, title:(Thunar)

windowrule = float, title:^(Save File)$
windowrule = size 1000 600, title:^(Save File)$
windowrule = center, title:^(Save File)$

windowrule = float, title:(CopyQ)$
windowrule = size 1000 600, title:(CopyQ)$
windowrule = center, title:(CopyQ)$

windowrule = float, title:^(Untitled - Google Chrome)$
windowrule = size 1000 600, title:^(Untitled - Google Chrome)$
windowrule = center, title:^(Untitled - Google Chrome)$

windowrule = float, title:^(Telegram)
windowrule = size 1300 700, title:^(Telegram)
windowrule = center, title:^(Telegram)

windowrule = float, title:^(ranger)$
windowrule = size 1300 700, title:^(ranger)$
windowrule = center, title:^(ranger)$

windowrule = float, title:^(Authentication Required — PolicyKit1 KDE Agent)$
windowrule = size 500 300, title:^(Authentication Required — PolicyKit1 KDE Agent)$
windowrule = center, title:^(Authentication Required — PolicyKit1 KDE Agent)$


windowrule = maximize, title:^(New Incognito Tab)
# windowrule = size 1300 700, title:^(New Incognito Tab)
# windowrule = center, title:^(New Incognito Tab)

windowrule = float, title:^(Mission Center)$
windowrule = size 1300 700, title:^(Mission Center)$
windowrule = center, title:^(Mission Center)$

windowrule = float, title:^(Open File)$
windowrule = size 1300 700, title:^(Open File)$
windowrule = center, title:^(Open File)$

windowrule = float, title:^(nwg-look)$
windowrule = size 1300 700, title:^(nwg-look)$
windowrule = center, title:^(nwg-look)$

windowrule = float, title:^(btop)$
windowrule = size 1300 800, title:^(btop)$
windowrule = center, title:^(btop)$

windowrule = float, ^(xarchiver)$
windowrule = size 1200 700, ^(xarchiver)$
windowrule = center, ^(xarchiver)$

windowrule = float, title:^(Easy Effects)$
windowrule = size 1000 600, title:^(Easy Effects)$
windowrule = center, title:^(Easy Effects)$

windowrule = float, title:^(Hourglass)$
windowrule = size 1000 600, title:^(Hourglass)$
windowrule = center, title:^(Hourglass)$

windowrule = float, title:^(Kvantum Manager)$
windowrule = size 1000 600, title:^(Kvantum Manager)$
windowrule = center, title:^(Kvantum Manager)$

windowrule = float, title:(Dolphin)$
windowrule = size 1000 600, title:(Dolphin)$
windowrule = center, title:(Dolphin)$
